// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/healthcheck.proto

package healthcheck

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`             // 服务名称
	InstanceID string `protobuf:"bytes,2,opt,name=instanceID,proto3" json:"instanceID,omitempty"` // 服务实例ID
	Url        string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`               // 客户端暴露的URL
	Timeout    int64  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`      // 过期时间
}

func (x *HealthCheckSRequest) Reset() {
	*x = HealthCheckSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_healthcheck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckSRequest) ProtoMessage() {}

func (x *HealthCheckSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_healthcheck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckSRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckSRequest) Descriptor() ([]byte, []int) {
	return file_proto_healthcheck_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckSRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheckSRequest) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *HealthCheckSRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthCheckSRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type HealthCheckSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMes string `protobuf:"bytes,1,opt,name=error_mes,json=errorMes,proto3" json:"error_mes,omitempty"` // 失败原因
}

func (x *HealthCheckSResponse) Reset() {
	*x = HealthCheckSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_healthcheck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckSResponse) ProtoMessage() {}

func (x *HealthCheckSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_healthcheck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckSResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckSResponse) Descriptor() ([]byte, []int) {
	return file_proto_healthcheck_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckSResponse) GetErrorMes() string {
	if x != nil {
		return x.ErrorMes
	}
	return ""
}

type HealthCheckCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`            // 服务实例ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`        // 服务名
	Host    string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`        // 服务Host
	Port    string `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`        // 服务Port
	Timeout int64  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"` // 过期时间
}

func (x *HealthCheckCRequest) Reset() {
	*x = HealthCheckCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_healthcheck_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckCRequest) ProtoMessage() {}

func (x *HealthCheckCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_healthcheck_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckCRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckCRequest) Descriptor() ([]byte, []int) {
	return file_proto_healthcheck_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckCRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HealthCheckCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheckCRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HealthCheckCRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *HealthCheckCRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type HealthCheckCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMes string `protobuf:"bytes,1,opt,name=error_mes,json=errorMes,proto3" json:"error_mes,omitempty"` // 失败原因
}

func (x *HealthCheckCResponse) Reset() {
	*x = HealthCheckCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_healthcheck_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckCResponse) ProtoMessage() {}

func (x *HealthCheckCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_healthcheck_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckCResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckCResponse) Descriptor() ([]byte, []int) {
	return file_proto_healthcheck_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckCResponse) GetErrorMes() string {
	if x != nil {
		return x.ErrorMes
	}
	return ""
}

var File_proto_healthcheck_proto protoreflect.FileDescriptor

var file_proto_healthcheck_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x75, 0x0a, 0x13, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x33, 0x0a,
	0x14, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x22, 0x7b, 0x0a, 0x13, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22,
	0x33, 0x0a, 0x14, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x32, 0xc2, 0x01, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x12, 0x20, 0x2e, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x12, 0x20, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x76, 0x72, 0x2f, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_healthcheck_proto_rawDescOnce sync.Once
	file_proto_healthcheck_proto_rawDescData = file_proto_healthcheck_proto_rawDesc
)

func file_proto_healthcheck_proto_rawDescGZIP() []byte {
	file_proto_healthcheck_proto_rawDescOnce.Do(func() {
		file_proto_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_healthcheck_proto_rawDescData)
	})
	return file_proto_healthcheck_proto_rawDescData
}

var file_proto_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_healthcheck_proto_goTypes = []any{
	(*HealthCheckSRequest)(nil),  // 0: healthcheck.HealthCheckSRequest
	(*HealthCheckSResponse)(nil), // 1: healthcheck.HealthCheckSResponse
	(*HealthCheckCRequest)(nil),  // 2: healthcheck.HealthCheckCRequest
	(*HealthCheckCResponse)(nil), // 3: healthcheck.HealthCheckCResponse
}
var file_proto_healthcheck_proto_depIdxs = []int32{
	0, // 0: healthcheck.HealthCheckService.HealthCheckS:input_type -> healthcheck.HealthCheckSRequest
	2, // 1: healthcheck.HealthCheckService.HealthCheckC:input_type -> healthcheck.HealthCheckCRequest
	1, // 2: healthcheck.HealthCheckService.HealthCheckS:output_type -> healthcheck.HealthCheckSResponse
	3, // 3: healthcheck.HealthCheckService.HealthCheckC:output_type -> healthcheck.HealthCheckCResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_healthcheck_proto_init() }
func file_proto_healthcheck_proto_init() {
	if File_proto_healthcheck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_healthcheck_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_healthcheck_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_healthcheck_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_healthcheck_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_healthcheck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_healthcheck_proto_goTypes,
		DependencyIndexes: file_proto_healthcheck_proto_depIdxs,
		MessageInfos:      file_proto_healthcheck_proto_msgTypes,
	}.Build()
	File_proto_healthcheck_proto = out.File
	file_proto_healthcheck_proto_rawDesc = nil
	file_proto_healthcheck_proto_goTypes = nil
	file_proto_healthcheck_proto_depIdxs = nil
}
